---
- name: Install and configure tomcat server for deployment
  hosts: nodes
  remote_user: root

  vars:
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat

  tasks:
    - name: Update system package
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat User
      user:
        name: '{{ tomcat_user }}'

    - name: Create Tomcat Group
      group:
        name: '{{ tomcat_user }}'

    - name: Create tomcat directory
      file:
        path: '{{ tomcat_path }}'
        owner: '{{ tomcat_user }}'
        group: '{{ tomcat_user }}'
        mode: 755
        recurse: yes

    - name: Download Tomcat and unarchive
      unarchive:
        src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
        dest: '{{ tomcat_path }}'
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Start tomcat server
      command: nohup {{ tomcat_path }}/bin/startup.sh

    - name: allow tcp connections
      command: sudo ufw allow 8080/tcp

    - name: connect to tomcat on port 8080
      tags:
        - test
        - connect
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status==200"
      retries: 2
      delay: 5
      notify:
        - Echo connection

  handlers:
    - name: Echo connection
      command: echo "success"



